version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules

  cli:
    build:
      context: .
      dockerfile: docker/cli/Dockerfile
    volumes_from:
      - web  
    links:
      - web
